Script started on 2015年03月10日 (週二) 17時28分15秒
]0;F74026137@2015cpp: ~/lab1F74026137@2015cpp:~/lab1$ whoami;pwd
F74026137
/home/F74026137/lab1
]0;F74026137@2015cpp: ~/lab1F74026137@2015cpp:~/lab1$ git config -l
user.name=F74026137
user.email=ann831210@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.lab1.url=https://github.com/F74026137/lab1.git
remote.lab1.fetch=+refs/heads/*:refs/remotes/lab1/*
]0;F74026137@2015cpp: ~/lab1F74026137@2015cpp:~/lab1$ git clone gtt[K[K[Khttps://github.com/<you[K[K[K[KF74026137/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;F74026137@2015cpp: ~/lab1F74026137@2015cpp:~/lab1$ exit

Script done on 2015年03月10日 (週二) 17時31分44秒
