Script started on 2015年03月13日 (週五) 18時09分47秒
]0;F74026137@2015cpp: ~/lab1F74026137@2015cpp:~/lab1$ who[K[K[Kvi lab1_B.cppgit push -u lab1 mastercommit[Kpush -u lab1 master[10Pvi lab1_B.cppgit push -u lab1 mastercommit[Kadd lab1.script[6Pconfig -lls[Kcd ..[3Plsgit config -ladd lab1.script[9Pcommitpush -u lab1 master[10Pvi lab1_B.cpp[Kvi lab1_B.cppgit push -u lab1 mastercommit[Kadd lab1.script[6Pconfig -lls[Kcd ..[3Plsgit config -ladd lab1.script[9Pcommitpush -u lab1 master[10Pvi lab1_B.cpp[Kg=[K++ -o lab1_b lab1_b[KB.cpp
]0;F74026137@2015cpp: ~/lab1F74026137@2015cpp:~/lab1$ ./lab1_b
Input:22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
]0;F74026137@2015cpp: ~/lab1F74026137@2015cpp:~/lab1$ cat lab1_b.script
]0;F74026137@2015cpp: ~/lab1F74026137@2015cpp:~/lab1$ exit

Script done on 2015年03月13日 (週五) 18時11分23秒
